name: TREVITE
favicon: null
layout_spectrum: 0.78871
typography_spectrum: 0.08809
title: 'СТРЪКОВЕ, КЪЛНОВЕ, ЗДРАВОСЛОВНИ ХРАНИ, СУПЕРХРАНИ'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#245921'
    - '#cdccd2'
    - '#4d9535'
    - '#112210'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
