name: trevite
favicon: null
layout_spectrum: 0.7231135359033942
typography_spectrum: 0.04479
title: СТРЪКОВЕ КЪЛНОВЕ ЗДРАВОСЛОВНИ ХРАНИ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#004500'
    - '#868682'
    - '#bebeaa'
    - '#17a400'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
