name: TREVITE
favicon: null
layout_spectrum: 0.19424
typography_spectrum: 0.04133
title: СТРЪКОВЕ - SUPER FOOD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afbbaf'
    - '#202a1f'
    - '#569500'
    - '#d7e8d8'
    - '#91c421'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
