name: TREVITE
favicon: null
layout_spectrum: 0.78871
typography_spectrum: 0.03542
title: 'СТРЪКОВЕ, КЪЛНОВЕ, ЗДРАВОСЛОВНИ ХРАНИ, СУПЕРХРАНИ'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefffa'
    - '#2e5600'
    - '#a0abcb'
    - '#dd8935'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
